<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tentangaplikasi extends CI_Controller
{

    public function index()
    {
       
        $this->load->view('template/header');
        $this->load->view('tentangaplikasi/tentangaplikasi');
        $this->load->view('template/footer');
    }

}

/* End of file Fasilitas.php */
/* Location: ./application/controllers/Fasilitas.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-11-21 20:46:29 */
/* http://harviacode.com */